### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by golergka** [dbt-labs/dbt-jsonschema#1]
I'd like to use this schemas in my work, but I don't want to infringe on your intellectual property. Was this originally intended as open source? And if it was, would you mind adding a license of your choice?

**Comment by gwenwindflower** [comment]
@golergka we're adding an apache license, same as dbt-core, thanks for asking about this! we're also going to finish getting this mapped shortly and link it to the [schema store](https://www.schemastore.org/json/) so it can power completion and all the other fun things in YAML LSPs that use the schemastore for definitions.
