### ISSUE TITLE
Add materialized view configs to dbt_project.yml

### ISSUE THREAD

**Issue by cmcnicoll** [dbt-labs/dbt-jsonschema#107]
Getting `Incorrect type. Expected "null"` for `auto_refresh`, `backup` and `on_configuration_change`.

Here are the docs for [Core](https://docs.getdbt.com/docs/build/materializations#materialized-view) and [Redshift](https://docs.getdbt.com/reference/resource-configs/redshift-configs#materialized-views).

**Comment by joellabes** [comment]
@cmcnicoll thanks for opening this - should be resolved now!
