### ISSUE TITLE
Add support for dbt 1.7

### ISSUE THREAD

**Issue by jeremyyeo** [dbt-labs/dbt-jsonschema#109]
I'm not too too in the know about how exactly this works but it appears that we don't yet support dbt 1.7 - just based on the folder structure I see in https://github.com/dbt-labs/dbt-jsonschema/tree/main/schemas.

dbt 1.7 is currently the latest version when creating new environments in dbt Cloud.

**Comment by dave-connors-3** [comment]
dude you're so right! long overdue -- lemme get the open PR merged into 1.6, then i can copy over that into 1.7, and we can tackle a few of the other issues that are specific to 1.7! thanks for the nudge
