### ISSUE TITLE
dbt_project.yaml does not recognize string type in +snowflake_warehouse

### ISSUE THREAD

**Issue by jeremy-thomas-roc** [dbt-labs/dbt-jsonschema#114]
Using the dbt Power User extension, this what I see in my dbt_project.yaml:

![image](https://github.com/dbt-labs/dbt-jsonschema/assets/104776437/8c85d373-23fa-4137-86f1-8d9aa8c04280)

Using dbt 1.4.5

**Comment by joellabes** [comment]
We added support in https://github.com/dbt-labs/dbt-jsonschema/pull/111 so it's available for 1.6 and 1.7, but as a rule we haven't been backporting missing keys all the way back - if you wanted to open a PR adding support we'd merge it!

**Comment by jeremy-thomas-roc** [comment]
@joellabes Currently using dbt 1.7 and this is still an issue, only in the `seeds` section of the yaml

![image](https://github.com/user-attachments/assets/b5affa66-c2ba-43a7-98d1-a44dbfaa4e59)

**Comment by joellabes** [comment]
Thanks! fixed now 🔨
