### ISSUE TITLE
Create tags pinned with dbt version to ease usage

### ISSUE THREAD

**Issue by H-Max** [dbt-labs/dbt-jsonschema#123]
I use the jsonSchema.xml file in IntelliJ to validate the YAML files in my dbt projects.

This method uses a URL to the JSON files in this repo (for instance: https://raw.githubusercontent.com/dbt-labs/dbt-jsonschema/main/schemas/packages.json) and I'd like to pin a specific version, not use the latest one.

Using tags would make this possible I believe, to pin the dbt version in the URL.

Thanks !

**Comment by dave-connors-3** [comment]
hey @H-Max! We use separate directories [here](https://github.com/dbt-labs/dbt-jsonschema/tree/main/schemas) to separate the schemas by version -- for example, you could update that link to `https://raw.githubusercontent.com/dbt-labs/dbt-jsonschema/main/schemas/1.6/packages-1.6.json` if you were on 1.6. 

Hope that helps!

**Comment by H-Max** [comment]
Hey, thx @dave-connors-3 for the info, I'm closing the issue !
