### ISSUE TITLE
Missing configuration for labels (used in BigQuery adapter)

### ISSUE THREAD

**Issue by kodaho** [dbt-labs/dbt-jsonschema#18]
Thanks for the creation of these JSON schemas. Very helpful!

I noticed that the labels configuration specific to the BigQuery adapter is not currently supported.
Because of that, the values of the dictionary used to define labels are considered as invalid (see screenshot below).
![image](https://user-images.githubusercontent.com/23268819/192169005-c00f2688-5870-4fe9-9e0d-fd6ad67a726f.png)

I would be happy to open a PR to add support for that if is OK to add BigQuery specific configuration in those schemas!

**Comment by joellabes** [comment]
Hi @kodaho, yes I'd be happy to merge a BQ-focused PR as long as it included a description that clarified that the dictionary only works/is needed on BQ 👍 

Example of a description property: https://github.com/dbt-labs/dbt-jsonschema/blob/bcaa4603b36bd515c9366cedca38b07214b9f7ec/schemas/dbt_yml_files.json#L466-L469

**Comment by kodaho** [comment]
Ok perfect I will start working on that!
