### ISSUE TITLE
Jinja in dbt_project.yml labels gives regex error

### ISSUE THREAD

**Issue by kieronellis** [dbt-labs/dbt-jsonschema#24]
Including Jinja brackets in a label results in error "String does not match pattern of ^[a-z0-9_-]{0,64}$".
![image](https://user-images.githubusercontent.com/69465049/207368407-60721c41-c4e4-45d0-b998-38f54782a3bd.png)

We also follow [SQLFluff rule](https://docs.sqlfluff.com/en/stable/rules.html#sqlfluff.rules.Rule_L046) to use a space before and after the jinja brackets, which would fail this regex.
```
class Rule_L046(code, description, **kwargs)
Jinja tags should have a single whitespace on either side.
```

**Comment by joellabes** [comment]
Hey @kieronellis, good callout! It looks like this doesn't have jinja strings included as an option. If you wanted to fix this, it would be something like this: 

Pull the [jinja string here](https://github.com/dbt-labs/dbt-jsonschema/blob/5452dce292a7e847b93b818e3cd163f39a0b3ce2/schemas/dbt_project.json#L139-L142) out into its own definition in the `"$defs"` object:
```
"jinja_string": {
      "type": "string",
      "pattern": "\\{\\{.*\\}\\}"
  },
```

Change [`boolean_or_jinja_string`](https://github.com/dbt-labs/dbt-jsonschema/blob/5452dce292a7e847b93b818e3cd163f39a0b3ce2/schemas/dbt_project.json#L137-L147) to ref the new `jinja_string` def:
```
  "boolean_or_jinja_string": {
      "oneOf": [
          {
              "$ref": "#/$defs/jinja_string"
          },
          {
              "type": "boolean"
          }
      ]
  },
```

In [`label_configs`](https://github.com/dbt-labs/dbt-jsonschema/blob/5452dce292a7e847b93b818e3cd163f39a0b3ce2/schemas/dbt_project.json#L148-L159), change the patternProperties to be a `oneOf`: 
```
  "patternProperties": {
      "^[a-z][a-z0-9_-]{0,63}$": {
          "oneOf": [
              {
                  "type": "string",
                  "pattern": "^[a-z0-9_-]{0,64}$"
              },
              {
                  "$ref": "#/$defs/jinja_string"
              }
          ]
      }
  },

```

You can validate that this is passing by adding the definition you were trying to use to this example file: https://github.com/dbt-labs/dbt-jsonschema/blob/main/tests/dbt_project.yml

Let me know if you need any help!
