### ISSUE TITLE
"enabled" and some other properties setup in "model_configs" were not setup in "seed_configs": dbt_project.json

### ISSUE THREAD

**Issue by lfelipe94** [dbt-labs/dbt-jsonschema#27]
There are some seeds where extra configuration is needed. For example, using the "dbt_project_evaluator" package: https://github.com/dbt-labs/dbt-project-evaluator requires to "disable" one seed as the image below:

![image](https://user-images.githubusercontent.com/105565603/210433478-cb0a838e-b304-4db0-a156-05d4dd520d88.png)

However, enabled and database are not in the "Seed_configs" in the dbt_project.json, therefore it shows the error. Also, "copy_grants" is not defined for models or seeds.

dbt_project.json:

![image](https://user-images.githubusercontent.com/105565603/210433311-7f585f54-7f93-417b-b7ef-73cece9db30e.png)

Is it ok to update the models configs and include some of them to the seeds to avoid this?

**Comment by joellabes** [comment]
Yes I would welcome a PR to fix this! Let me know if you need any help with the JSON Schema syntax. You could also add a more complex dbt_project.yml file to the tests directory and the [ci.yml](https://github.com/dbt-labs/dbt-jsonschema/blob/main/.github/workflows/ci.yml#L26-L27)
