### ISSUE TITLE
'Loader' property "not allowed" where it should be

### ISSUE THREAD

**Issue by AaronCoquet-Easypark** [dbt-labs/dbt-jsonschema#28]
In a `sources.yaml` file, the json-schema indicates that `loader: <str>` is not valid within a `tables:` dict, when it is actually allowed there.
![image](https://user-images.githubusercontent.com/110165637/210553497-d3fc74ec-5ea2-44dc-a4b1-3c626e1bab27.png)
![image](https://user-images.githubusercontent.com/110165637/210553732-356f75d2-b18b-4e82-9e23-a19065219986.png)
![image](https://user-images.githubusercontent.com/110165637/210553779-f361615d-2569-40c6-ac0e-8f09c3a71fd0.png)

**Comment by joellabes** [comment]
Good spotting! I'd welcome a PR to fix this 🛠️
