### ISSUE TITLE
Add descriptions to use the JSON schema in JetBrains to README

### ISSUE THREAD

**Issue by yu-iskw** [dbt-labs/dbt-jsonschema#53]
We are able to take advantage of the JSON schema in JetBrains as well. It would be great to briefly explain how to set up property of the JSON schema mapping in JetBrains like PyCharm.

https://yu-ishikawa.medium.com/dbt-yaml-validator-in-jetbrains-b5ef25e9253e

**Comment by joellabes** [comment]
Amazing! I'd welcome a PR to the readme that adds the summary of how to do this based on your article + a link to the source.

**Comment by yu-iskw** [comment]
@joellabes Alright. I will send a pull request about that. 

Besides, I think the repository with the JSON schemas are quite useful to get more production on the development of dbt projects. It would be great to post it to the dbt developer blog so that the knowledge is shared with more dbt users. If there is anything I can help, please let me know.

**Comment by yu-iskw** [comment]
@joellabes We can close the issue. Please let me know, if there is anything I can help more.
