### ISSUE TITLE
Sync `dbt_yml_files.json` spec with the current `metrics` spec

### ISSUE THREAD

**Issue by waligob** [dbt-labs/dbt-jsonschema#58]
The [json schema in `dbt_yml_files.json`](https://github.com/dbt-labs/dbt-jsonschema/blob/9c334f49a43173e1efe0962f1f4aba92beebac01/schemas/dbt_yml_files.json#L164-L239) conflicts with the current [`metrics` config spec](https://docs.getdbt.com/docs/build/metrics#available-properties). For example, `dbt_yml_files.json` specifies `type` as a required property, even though it appears this is [no longer a supported property](https://docs.getdbt.com/docs/build/metrics#available-properties).

**Comment by joellabes** [comment]
Good call-out! I'd welcome a PR to update this otherwise we will likely catch it in our prep for 1.5 support

**Comment by dave-connors-3** [comment]
@waligob Hey Brian! This should be resolved, can you confirm on your end that you're seeing the intended behavior?

**Comment by waligob** [comment]
Confirmed that the schema is working as expected with `metrics`. Thanks!
