### ISSUE TITLE
Add docs-paths config to dbt_project.yml

### ISSUE THREAD

**Issue by jaypeedevlin** [dbt-labs/dbt-jsonschema#9]
For the configuration

```yml
docs-paths: ["models", "docs"]
```

I am getting `Property docs-paths is not allowed.`

**Comment by joellabes** [comment]
This is pretty easy to add! Just looks like this: 
https://github.com/dbt-labs/dbt-jsonschema/blob/main/schemas/dbt_project.json#L51-L53

but docs-paths instead of model-paths

**Comment by joellabes** [comment]
Resolved in https://github.com/dbt-labs/dbt-jsonschema/commit/0d5dce7b1b215fbd425c27f4a571af35088d930b
