### ISSUE TITLE
Add `grants` to dbt_project.yml model configs

### ISSUE THREAD

**Issue by dpguthrie** [dbt-labs/dbt-jsonschema#97]
When adding grants to `dbt_project.yml` you curently see "Incorrect type.  Expected "null".

![image](https://github.com/dbt-labs/dbt-jsonschema/assets/10198967/2a82ebb0-004e-46cd-8714-d82efab42c3c)

**Comment by dave-connors-3** [comment]
Thanks for raising this one @dpguthrie! grabbing this noe
